name: hemis_test
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  equatable: ^2.0.7
  dartz: ^0.10.1
  dio: ^5.8.0+1
  freezed_annotation: ^2.4.1
  provider: ^6.1.5
  liquid_progress_indicator_v2: ^0.5.0
  shimmer: ^3.0.0
  lottie: ^3.3.1
  flutter_svg: ^2.1.0
  mask_text_input_formatter: ^2.9.0
  intl: ^0.20.2
  connectivity_plus: ^6.1.4
  logger: ^2.5.0
  another_flushbar: ^1.12.30
  vibration: ^3.1.3
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  freezed: ^2.5.2
  json_serializable: ^6.5.4

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/


  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/dmsans/DMSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/dmsans/DMSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/dmsans/DMSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/dmsans/DMSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/dmsans/DMSans-Light.ttf
          weight: 300
        - asset: assets/fonts/dmsans/DMSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/dmsans/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/dmsans/DMSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/dmsans/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/dmsans/DMSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/dmsans/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/dmsans/DMSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/dmsans/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/dmsans/DMSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/dmsans/DMSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/dmsans/DMSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/dmsans/DMSans-Black.ttf
          weight: 900
        - asset: assets/fonts/dmsans/DMSans-BlackItalic.ttf
          weight: 900
          style: italic

    - family: Unbounded
      fonts:
        - asset: assets/fonts/unbounded/Unbounded-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/unbounded/Unbounded-Light.ttf
          weight: 300
        - asset: assets/fonts/unbounded/Unbounded-Regular.ttf
          weight: 400
        - asset: assets/fonts/unbounded/Unbounded-Medium.ttf
          weight: 500
        - asset: assets/fonts/unbounded/Unbounded-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/unbounded/Unbounded-Bold.ttf
          weight: 700
        - asset: assets/fonts/unbounded/Unbounded-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/unbounded/Unbounded-Black.ttf
          weight: 900